### ISSUE TITLE
Todo list open sourcing

### ISSUE THREAD

**Issue by sderuiter** [ccdexplorer/.github#2]
- [x] Purchase ccdexplorer.io domain
- [x] Create ccdexplorer Github org
- [x] Publish the shared codebase `ccdefundamentals`
- [x] Pusblish the recurring repo
- [x] Publish the heartbeat repo, that fills the db
- [x] Publish the API
- [x] Publish the main site
- [x] Publish the bot
- [x] Publish the nightly accounts generator
- [x] Publish the statistics generator
